openapi: 3.1.0
info:
  title: Deprecated Custom GPT Action API
  version: 0.0.0
  description: |
    Deprecated.

    This repository no longer treats the TypeScript/Cloudflare Action API as the supported integration path.
    The supported runtime is the Python FastMCP server (`uv run kb mcp-server`).

    For ChatGPT MCP, use OAuth2 Authorization Code with PKCE (S256) against the Python MCP deployment.
servers: []
paths: {}
